version: '3'

services:

  laravel:
    build: 
      context: ./php
      dockerfile: Dockerfile.prod
    image: edsonnhancale/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: edsonnhancale/nginx:prod
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - laranet

networks:
  laranet:
    driver: bridge